### ISSUE TITLE
How to get the course resources?

### ISSUE THREAD

**Issue by zhongweili** [ZhengHe-MD/ir-freiburg#1]
What a great course notes!

Want to know how to download slides and codes in the [page](https://daphne.informatik.uni-freiburg.de/cas/login?service=https%3A%2F%2Fdaphne.informatik.uni-freiburg.de%2Fws1718%2FInformationRetrieval%2Fsvn%2Fpublic%2Fslides%2Flecture-10.pdf&gateway=true) that requires registration.

**Comment by ZhengHe-MD** [comment]
checkout lecture svn repo in the References part of README.md @zhongweili
